/**
 * SERVICIO DE GENERACIÓN AUTOMÁTICA DE COTIZACIONES
 * 
 * Genera cotizaciones solares completas de manera automática usando:
 * - Datos OCR extraídos de recibos
 * - Análisis de consumo
 * - Tariff pricing
 * - Cálculos de ROI automáticos
 */

import logger from '../../config/logger.js';

export interface AutoGeneratedQuotation {
  success: boolean;
  quotation: {
    clientName: string;
    clientEmail?: string;
    serviceNumber: string;
    currentConsumption: number; // kWh/mes
    systemSize: number; // kW
    panelCount: number;
    estimatedMonthlySavings: number; // $
    investmentAmount: number; // $
    paybackMonths: number;
    roi25Years: number;
    tariffType: string;
    createdBy: string; // 'IA_AUTO_GENERATED'
    notes: string;
  };
  metadata: {
    confidenceScore: number;
    assumptionsUsed: string[];
    warnings: string[];
  };
}

class QuotationGeneratorService {
  private readonly COST_PER_PANEL = 8500; // $
  private readonly PANEL_CAPACITY = 0.41; // kW por panel
  private readonly SYSTEM_EFFICIENCY = 0.85; // 85% de eficiencia
  private readonly TARIFF_RATES: { [key: string]: number } = {
    'T1': 7.50, // $/kWh
    'GDMTO': 8.20,
    'GDMTH': 9.10,
    'DAC': 12.50,
    'HM': 6.80,
    'SEM': 10.20,
  };

  /**
   * Generar cotización automáticamente desde datos OCR
   */
  generateFromOCR(ocrData: {
    serviceNumber: string;
    clientName?: string;
    clientEmail?: string;
    consumptionKWh: number;
    tariffType?: string;
    currentAmount?: number;
  }): AutoGeneratedQuotation {
    const assumptions: string[] = [];
    const warnings: string[] = [];
    let confidenceScore = 0.7; // Baseline confidence

    // Validar datos mínimos requeridos
    if (!ocrData.consumptionKWh || ocrData.consumptionKWh < 50) {
      throw {
        statusCode: 400,
        message: 'Consumo insuficiente para cotización solar',
        details: { provided: ocrData.consumptionKWh }
      };
    }

    // Tariff type
    let tariffType = ocrData.tariffType || 'T1';
    if (!this.TARIFF_RATES[tariffType]) {
      tariffType = 'T1';
      warnings.push(`Tariff type '${ocrData.tariffType}' no reconocido, usando T1 por defecto`);
      confidenceScore -= 0.1;
    }

    // Consumo mensual (validar)
    const monthlyConsumption = Math.max(50, Math.min(5000, ocrData.consumptionKWh));
    if (monthlyConsumption !== ocrData.consumptionKWh) {
      assumptions.push(`Consumo ajustado de ${ocrData.consumptionKWh} a ${monthlyConsumption} kWh`);
      confidenceScore -= 0.05;
    }

    // Calcular tamaño del sistema
    // Sistema dimensionado para cubrir 80% del consumo (25% más capacidad para invierno/nubosidad)
    const coveredConsumption = monthlyConsumption * 0.80;
    const requiredCapacity = coveredConsumption / 30 / 4; // 30 días, 4 horas pico promedio
    const systemSizeKW = Math.ceil(requiredCapacity / 0.5) * 0.5; // Redondear a 0.5kW
    
    assumptions.push(`Sistema dimensionado para cubrir 80% del consumo (${coveredConsumption.toFixed(0)} kWh)`);

    // Cantidad de paneles
    const panelCount = Math.ceil(systemSizeKW / this.PANEL_CAPACITY);
    const investmentAmount = panelCount * this.COST_PER_PANEL;

    // Generación anual esperada
    const dailyPeakHours = 4; // Horas pico promedio en México
    const monthlyGeneration = systemSizeKW * 30 * dailyPeakHours * this.SYSTEM_EFFICIENCY;
    
    assumptions.push(`Generación mensual estimada: ${monthlyGeneration.toFixed(0)} kWh`);

    // Ahorros mensuales
    const tariffRate = this.TARIFF_RATES[tariffType];
    const monthlyAverageCost = monthlyConsumption * tariffRate;
    const estimatedAhorros = monthlyGeneration * tariffRate * 0.80; // 80% del generado (rest to grid)
    
    // Si OCR tiene monto actual, usar para validación
    if (ocrData.currentAmount) {
      const expectedCost = monthlyConsumption * tariffRate;
      if (Math.abs(expectedCost - ocrData.currentAmount) > expectedCost * 0.2) {
        warnings.push('Costo actual del OCR difiere del cálculo esperado');
        confidenceScore -= 0.15;
      }
    } else {
      assumptions.push(`Tarifa de ${tariffType} estimada en $${tariffRate.toFixed(2)}/kWh`);
    }

    // Payback period (meses)
    const paybackMonths = Math.round(investmentAmount / estimatedAhorros);

    // ROI a 25 años
    const yearsOperating = 25;
    const totalSavings = estimatedAhorros * 12 * yearsOperating;
    const roi25Years = ((totalSavings - investmentAmount) / investmentAmount) * 100;

    // Validar ROI razonable
    if (roi25Years < 100 || roi25Years > 10000) {
      warnings.push(`ROI calculado parece fuera de rango (${roi25Years.toFixed(0)}%)`);
      confidenceScore -= 0.2;
    }

    logger.info({
      message: 'Quotation auto-generated from OCR',
      serviceNumber: ocrData.serviceNumber,
      systemSize: systemSizeKW,
      panelCount,
      paybackMonths,
      roi25Years: roi25Years.toFixed(0),
      confidenceScore: confidenceScore.toFixed(2)
    });

    return {
      success: true,
      quotation: {
        clientName: ocrData.clientName || 'Cliente Automatizado',
        clientEmail: ocrData.clientEmail,
        serviceNumber: ocrData.serviceNumber,
        currentConsumption: monthlyConsumption,
        systemSize: systemSizeKW,
        panelCount,
        estimatedMonthlySavings: Math.round(estimatedAhorros * 100) / 100,
        investmentAmount,
        paybackMonths: Math.max(1, paybackMonths), // Min 1 month
        roi25Years: Math.round(roi25Years * 100) / 100,
        tariffType,
        createdBy: 'IA_AUTO_GENERATED',
        notes: `Cotización generada automáticamente el ${new Date().toLocaleDateString('es-MX')}. Sistema dimensionado para cubrir 80% del consumo.`
      },
      metadata: {
        confidenceScore: Math.max(0, Math.min(1, confidenceScore)),
        assumptionsUsed: assumptions,
        warnings
      }
    };
  }

  /**
   * Validar que una cotización generada sea razonable
   */
  validateQuotation(quotation: AutoGeneratedQuotation['quotation']): {
    valid: boolean;
    issues: string[];
  } {
    const issues: string[] = [];

    // Validar payback
    if (quotation.paybackMonths < 12 || quotation.paybackMonths > 240) {
      issues.push(`Payback fuera de rango: ${quotation.paybackMonths} meses (esperado: 12-240)`);
    }

    // Validar ROI
    if (quotation.roi25Years < 100 || quotation.roi25Years > 5000) {
      issues.push(`ROI fuera de rango: ${quotation.roi25Years}% (esperado: 100-5000%)`);
    }

    // Validar proporción ahorros/inversión
    const monthlyToAnnual = quotation.estimatedMonthlySavings * 12;
    const roi1Year = (monthlyToAnnual / quotation.investmentAmount) * 100;
    if (roi1Year < 5 || roi1Year > 50) {
      issues.push(`ROI del 1er año fuera de rango: ${roi1Year}%`);
    }

    // Validar tamaño sistema vs consumo
    const generationCapacity = quotation.systemSize * 30 * 4 * 0.85; // kWh/mes
    if (generationCapacity < quotation.currentConsumption * 0.6) {
      issues.push(`Sistema parece muy pequeño (genera ${generationCapacity}kWh vs ${quotation.currentConsumption}kWh consumo)`);
    }

    return {
      valid: issues.length === 0,
      issues
    };
  }

  /**
   * Mejorar calidad de cotización si hay datos adicionales
   */
  enrichQuotation(
    quotation: AutoGeneratedQuotation['quotation'],
    enrichmentData?: {
      roofArea?: number;
      roofOrientation?: string;
      cloudCoveragePercent?: number;
      inverterType?: string;
    }
  ): AutoGeneratedQuotation['quotation'] {
    if (!enrichmentData) return quotation;

    // Ajustar por cobertura de nubes
    if (enrichmentData.cloudCoveragePercent) {
      const efficiencyFactor = 1 - (enrichmentData.cloudCoveragePercent / 100) * 0.3;
      quotation.estimatedMonthlySavings *= efficiencyFactor;
    }

    // Ajustar por orientación de techo (ideal: Sur en México)
    if (enrichmentData.roofOrientation) {
      const orientationFactors: { [key: string]: number } = {
        'south': 1.0,
        'southeast': 0.95,
        'southwest': 0.95,
        'east': 0.85,
        'west': 0.85,
        'north': 0.6
      };
      const factor = orientationFactors[enrichmentData.roofOrientation.toLowerCase()] || 0.9;
      quotation.estimatedMonthlySavings *= factor;
    }

    // Recalcular payback y ROI con valores ajustados
    const newPayback = quotation.investmentAmount / quotation.estimatedMonthlySavings;
    quotation.paybackMonths = Math.round(newPayback);

    const newROI = ((quotation.estimatedMonthlySavings * 12 * 25 - quotation.investmentAmount) / quotation.investmentAmount) * 100;
    quotation.roi25Years = Math.round(newROI * 100) / 100;

    return quotation;
  }
}

export default new QuotationGeneratorService();
